sudo: required

language: crystal

crystal:
  - latest
  - nightly
  
script:
  - crystal spec
  - ./bin/crystal-coverage spec/mpngin_spec.cr

services: redis-server

matrix:
  allow_failures:
    - crystal: nightly